---
<h1><center>Foundations of Deep Learning</center></h1>
<center>Winter Semester 2017/2018</center>


---
<center>Group members:</center>
<center>October 17, 2018</center>

---
<h2><center>Exercise 01</center></h2>

2) **Eigenvalue Decomposition**

Given the matrix

\begin{equation*}
A = 
\frac{1}{4} \begin{bmatrix}
7 & -\sqrt{3} \\
-\sqrt{3} & 5
\end{bmatrix}
\end{equation*}

(a) Compute the eigenvalue decomposition $A = \begin{equation} Q \Lambda Q^{T}\end{equation}$ with $\Lambda = diag(\lambda_1, \lambda_2)$

In [9]:
import numpy as np
from numpy import diag, dot, inf
from numpy.linalg import eig, inv, norm

# Define matrix
A = (1/4) * np.matrix([[7, -np.sqrt(3)],[-np.sqrt(3), 5]])
print("Matrix A: ", A)
print()

# Calculate eigendecomposition
w, v = eig(A)
print("Eigenvalues of A: ", w)
print("Eigenvectors of A: ")
print(v[:,0])
print(v[:,1])
print()

# Define elements for eigendecomposition
Q = v
Q_inv = inv(Q)
L = diag(w)


# Reconstruct original matrix A
B = Q.dot(L).dot(Q_inv)
print("Reconstructed Matrix B: ", B)

# Confirm first eigenvector (B and C should be the same) -> For feedback
B = A.dot(v[:, 0])
C = v[:, 0] * w[0]

Matrix A:  [[ 1.75      -0.4330127]
 [-0.4330127  1.25     ]]

Eigenvalues of A:  [2. 1.]
Eigenvectors of A: 
[[ 0.8660254]
 [-0.5      ]]
[[0.5      ]
 [0.8660254]]

Reconstructed Matrix B:  [[ 1.75      -0.4330127]
 [-0.4330127  1.25     ]]


(b) Show that the columns of $Q$ are orthonormal, i.e. the columns are of unit length and orthogonal.

In [18]:
# Define transpose of Q
Q_trans = Q.transpose()

# For orthogonal matrices, multiplication of a matrix by its transpose results in the identity matrix 
print(np.matmul(Q, Q_trans))
print()

# Check if each eigenvector has module 1
for i in range(Q.shape[0]):
    print("Vector: ", Q[:,i])
    print("Vector norm: ", norm(Q[:,i]))
    i += 1
    
##

B = np.matrix([[(np.sqrt(3)/3), -np.sqrt(3)],[1, 1]])
print(B)


[[1. 0.]
 [0. 1.]]

Vector:  [[0.96592583]
 [0.25881905]]
Vector norm:  1.0
Vector:  [[-0.25881905]
 [ 0.96592583]]
Vector norm:  1.0
[[ 0.57735027 -1.73205081]
 [ 1.          1.        ]]


(c) Show that the matrix $Q\Lambda^{-1}Q^T$ with $\Lambda^{-1} = diag(\lambda_1^{-1}, \lambda_2^{-1})$ is the inverse of $A$

In [3]:
# Define inverse of Lambda
L_inv = inv(L)

# Showing that this matrix...
print(Q.dot(L_inv).dot(Q_trans))
print()

# ...is equal to the inverse of A
print("Invese of A: ", inv(A))


[[0.625      0.21650635]
 [0.21650635 0.875     ]]

Invese of A:  [[0.625      0.21650635]
 [0.21650635 0.875     ]]


(d) For course improvements, we would like your feedback about this question. At least tell us how
much time you did invest, if you had major problems and if you think it’s useful.

-> Write feedback from (a)

3) **Matrix inversion**

Given the matrix

\begin{equation*}
A = 
\begin{bmatrix}
3 & 4 \\
6 & 13
\end{bmatrix}
\end{equation*}

(a) Compute the LU decomposition of it, i.e. $A = L \cdot U$, where $L$ is a lowertriangular matrix and $U$ is an uppertriangular matrix. Use this decomposition to solve $A \cdot x = b$ with $b = (1,2)^{T}$ via forward
and backward substitution.

In [4]:
from scipy.linalg import lu

# Define Matrix
A = np.matrix([[3, 4],[6, 13]])

# LU Decomposition, where P: Permutation matrix, L: Lower triangular matrix and U: Upper triangular matrix
P, L, U = lu(A, permute_l=False)

print("L: ", L)
print("U: ", U)
print()

# A*x = b -> (LU)*x = b -> x = ((LU)^-1)*b -> x = (U^-1)*(L^-1)*b

U_inv = inv(U)
L_inv = inv(L)
b = np.array([[1,2]]).transpose()
print("L_inv: ", L_inv)
print("U_inv: ", U_inv)
print("b: ", b)
print()

x = U_inv.dot(L_inv).dot(b)
print("x: ", x)
print()

# Result should be equal to b -> RETURNS THE TRANSPOSE
print(A.dot(x))

L:  [[1.  0. ]
 [0.5 1. ]]
U:  [[ 6.  13. ]
 [ 0.  -2.5]]

L_inv:  [[ 1.   0. ]
 [-0.5  1. ]]
U_inv:  [[ 0.16666667  0.86666667]
 [-0.         -0.4       ]]
b:  [[1]
 [2]]

x:  [[ 1.46666667]
 [-0.6       ]]

[[2.]
 [1.]]


(b) Use Gauss elimination to explicitly calculate the inverse of $A$ and show that it yields the same solution $x = A^{-1} \cdot b$ from part (a).

(c) For course improvements, we would like your feedback about this question. At least tell us how
much time you did invest, if you had major problems and if you think it’s useful.

4) **Vector Norms**

The length of a vector is not a single number but can be defined in different ways. These vector norms
share common properties but also have different characteristics.


(a) Compute the $\left\lVert \cdot \right\rVert_1$, $\left\lVert \cdot \right\rVert_2$, $\left\lVert \cdot \right\rVert_8$ and $\left\lVert \cdot \right\rVert_\infty$ norms of the following vectors:


$x_1 = \begin{bmatrix} 24  \\ 3 \\ 2 \\ 31 \end{bmatrix}$
,
$x_2 = \begin{bmatrix} 27  \\ 20 \\ 26 \\ 21 \end{bmatrix}$
,
$x_3 = \begin{bmatrix} 30  \\ 21 \\ 27 \\ 5 \end{bmatrix}$
and
$x_4 = \begin{bmatrix} 26  \\ 28 \\ 25 \\ 14 \end{bmatrix}$



In [12]:
# Define vectors
x_1 = np.array([24,3,2,31])
x_2 = np.array([27,20,26,21])
x_3 = np.array([30,21,27,5])
x_4 = np.array([26,28,25,14])

# Define norms of order 1
x_1_norm1 = norm(x_1, ord=1)
x_2_norm1 = norm(x_2, ord=1)
x_3_norm1 = norm(x_3, ord=1)
x_4_norm1 = norm(x_4, ord=1)

print(x_4_norm1)

# Define norms of order 2
x_1_norm2 = norm(x_1, ord=2)
x_2_norm2 = norm(x_2, ord=2)
x_3_norm2 = norm(x_3, ord=2)
x_4_norm2 = norm(x_4, ord=2)

print(x_4_norm2)

# Define norms of order 8
x_1_norm8 = norm(x_1, ord=8)
x_2_norm8 = norm(x_2, ord=8)
x_3_norm8 = norm(x_3, ord=8)
x_4_norm8 = norm(x_4, ord=8)

print(x_4_norm8)

# Define norms of order inf (max(abs(x)))
x_1_norm_inf = norm(x_1, ord=inf)
x_2_norm_inf = norm(x_2, ord=inf)
x_3_norm_inf = norm(x_3, ord=inf)
x_4_norm_inf = norm(x_4, ord=inf)

print(x_4_norm_inf)


93.0
47.75981574503821
30.458236965849625
28.0


(b) Draw the set of points with $\left\lVert x \right\rVert_i = 1$ for $i \in \left\{ 1, 2, 8, \infty \right\}$ and $x \in \mathbb{R}^{2}$

In [20]:
#TODO


(c) For course improvements, we would like your feedback about this question. At least tell us how
much time you did invest, if you had major problems and if you think it’s useful.

5) **Special Orthorgonal Matrices**

A very important class of matrices are the special orthogonal group _SO(n)_. These matrices are charac-
terized by a unit determinant and correspond to rotations around the origin.

(a) Given the matrix

\begin{equation*}
A = 
\frac{1}{4} \begin{bmatrix}
7 & \sqrt{3} \\
\sqrt{3} & 5
\end{bmatrix}
\end{equation*}

compute $det(A), Tr(A)$ and its eigenvalues.

In [7]:
from numpy.linalg import det

# Define matrix
A = (1/4) * np.matrix([[7, np.sqrt(3)],[np.sqrt(3), 5]])
print("Matrix A: ", A)
print()

# Calculate determinant and trace of A
print("Det of A: ", det(A))
print("Trace of A: ", np.trace(A))


Matrix A:  [[1.75      0.4330127]
 [0.4330127 1.25     ]]

Det of A:  1.9999999999999998
Trace of A:  3.0


(b) The matrix

\begin{equation*}
Q(\alpha) = 
\begin{bmatrix}
\cos(\alpha) & -\sin(\alpha) \\
\sin(\alpha) & \cos(\alpha)
\end{bmatrix}
\end{equation*}

represents a rotation around an axis by the angle $\alpha$. Compute $A´ = Q \cdot A \cdot Q^{T}, det(A´), Tr(A´)$ and its eigenvalues for $\alpha = \pi/12$

In [10]:
# Define alpha
alpha = np.pi/12

# Define Rotation matrix Q
Q = np.matrix([[np.cos(alpha), -np.sin(alpha)],[np.sin(alpha), np.cos(alpha)]])

# Calculate A'
A_quote = Q.dot(A).dot(Q.transpose())
print(A_quote)
print()

# Calculate determinant of A'
print("Determinant of A': ", det(A_quote))

# Calculate trace of A'
print("Trace of A': ", np.trace(A_quote))
print()

# Calculate eigendecomposition
w, v = eig(A_quote)
print("Eigenvalues of A': ", w)
print("Eigenvectors of A': ", v)
print()


[[1.5 0.5]
 [0.5 1.5]]

Determinant of A':  2.0
Trace of A':  3.0

Eigenvalues of A':  [1. 2.]
Eigenvectors of A':  [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]



(c) What would $A´$ be for $\alpha = \pi/3$

In [13]:
# Define new Rotation matrix
new_alpha = np.pi/3
Q = np.matrix([[np.cos(alpha), -np.sin(alpha)],[np.sin(alpha), np.cos(alpha)]])

# Calculate A'
A_quote = Q.dot(A).dot(Q.transpose())
print(A_quote)

(d) For course improvements, we would like your feedback about this question. At least tell us how
much time you did invest, if you had major problems and if you think it’s useful.